In [22]:
import pandas as pd

In [23]:
s = pd.Series([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64

Dataframes

In [24]:
data = {
    "name": ["Ankur","Bhawani","sonu"],
    "city": ["dholakpur","Jaipur","Udaipur"]
}

df = pd.DataFrame(data)

In [25]:
df

      name       city
0    Ankur  dholakpur
1  Bhawani     Jaipur
2     sonu    Udaipur

In [26]:
df.head() ##head or tail badi entities m use hote hai jisme head upr vala data print krta or tail niche vala

      name       city
0    Ankur  dholakpur
1  Bhawani     Jaipur
2     sonu    Udaipur

In [27]:
df.tail()

      name       city
0    Ankur  dholakpur
1  Bhawani     Jaipur
2     sonu    Udaipur

In [28]:
df.shape

(3, 2)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   city    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [30]:
df["name"]

0      Ankur
1    Bhawani
2       sonu
Name: name, dtype: str

In [31]:
df["city"]

0    dholakpur
1       Jaipur
2      Udaipur
Name: city, dtype: str

In [32]:
df.iloc[1]

name    Bhawani
city     Jaipur
Name: 1, dtype: str

In [33]:
df["age"]=[23,22,21]

In [34]:
df

      name       city  age
0    Ankur  dholakpur   23
1  Bhawani     Jaipur   22
2     sonu    Udaipur   21

In [35]:
df["country"] = "india"

In [36]:
df

      name       city  age country
0    Ankur  dholakpur   23   india
1  Bhawani     Jaipur   22   india
2     sonu    Udaipur   21   india

In [37]:
df[df["age"]>21]

      name       city  age country
0    Ankur  dholakpur   23   india
1  Bhawani     Jaipur   22   india

In [38]:
df["age after five years"]=df["age"]+5

In [39]:
df

      name       city  age country  age after five years
0    Ankur  dholakpur   23   india                    28
1  Bhawani     Jaipur   22   india                    27
2     sonu    Udaipur   21   india                    26

In [40]:
df.isnull()  ##agar koi entity khali hogi to vaha true print kr dega

    name   city    age  country  age after five years
0  False  False  False    False                 False
1  False  False  False    False                 False
2  False  False  False    False                 False

In [41]:
df.isnull().sum() ##total kitni null values hai

name                    0
city                    0
age                     0
country                 0
age after five years    0
dtype: int64

In [42]:
df.fillna(1)  ##null entities ko fill krne k kaam aata

      name       city  age country  age after five years
0    Ankur  dholakpur   23   india                    28
1  Bhawani     Jaipur   22   india                    27
2     sonu    Udaipur   21   india                    26

In [43]:
df.dropna() ##jis b row m nul value h us row ko hata dega

      name       city  age country  age after five years
0    Ankur  dholakpur   23   india                    28
1  Bhawani     Jaipur   22   india                    27
2     sonu    Udaipur   21   india                    26

In [44]:

mydataset = {
    "Cars": ["BMW" ,"VOLVO","Ford"],
    "Passings":[3,7,2]
}

In [46]:
df = pd.DataFrame(mydataset)
print(df)

    Cars  Passings
0    BMW         3
1  VOLVO         7
2   Ford         2

In [48]:
a=[1,4,6,9,3]
my=pd.Series(a)
myvar = pd.Series(a,["x","y","z","p","q"])
print(myvar)

x    1
y    4
z    6
p    9
q    3
dtype: int64

In [49]:
calories = {"day1":400 , "day2":500, "day3":390}
my = pd.Series(calories)
print(my)

day1    400
day2    500
day3    390
dtype: int64

In [50]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df=pd.DataFrame(data, index=["day1","day2","day3"])
print(df)
print(df.loc[["day1","day2"]])

      calories  duration
day1       420        50
day2       380        40
day3       390        45
      calories  duration
day1       420        50
day2       380        40

In [58]:
df = pd.read_csv("data1.csv")

In [60]:
df.shape

(32, 5)

In [52]:
print(df.head(10))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7        45  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0

In [53]:
print(df.tail())

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB

In [61]:
df.dropna()

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60  '2020/12/26'    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [63]:
df.dropna().shape

(29, 5)

In [65]:
x = df["Calories"].mode()[0]
print(x)

300.0

In [68]:
df["Date"]

0     '2020/12/01'
1     '2020/12/02'
2     '2020/12/03'
3     '2020/12/04'
4     '2020/12/05'
5     '2020/12/06'
6     '2020/12/07'
7     '2020/12/08'
8     '2020/12/09'
9     '2020/12/10'
10    '2020/12/11'
11    '2020/12/12'
12    '2020/12/12'
13    '2020/12/13'
14    '2020/12/14'
15    '2020/12/15'
16    '2020/12/16'
17    '2020/12/17'
18    '2020/12/18'
19    '2020/12/19'
20    '2020/12/20'
21    '2020/12/21'
22             NaN
23    '2020/12/23'
24    '2020/12/24'
25    '2020/12/25'
26    '2020/12/26'
27    '2020/12/27'
28    '2020/12/28'
29    '2020/12/29'
30    '2020/12/30'
31    '2020/12/31'
Name: Date, dtype: str