In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Used_bikes.csv")

In [4]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [5]:
df.head(7)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda

In [19]:
df.tail(9)

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield,11.0
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero,9.0
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj,14.0
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero,22.0
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero,7.0
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS,12.0
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj,9.0
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero,19.0
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj,16.0

In [7]:
df.shape

(32648, 8)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [20]:
df.dtypes

bike_name                str
price                float64
city                     str
kms_driven           float64
owner                    str
age                  float64
power                float64
brand                    str
age after 3 years    float64
dtype: object

In [22]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [24]:
df.duplicated().sum()

np.int64(25324)

In [27]:
df.drop_duplicates(inplace=True)
df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS,6.0
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield,7.0
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph,11.0
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS,7.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha,6.0
...,...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero,11.0
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj,12.0
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson,7.0
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj,7.0
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj,8.0

In [28]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["bike_name"]

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [29]:
df['bike_name'].unique()

<StringArray>
[      'TVS Star City Plus Dual Tone 110cc',
              'Royal Enfield Classic 350cc',
                     'Triumph Daytona 675R',
                     'TVS Apache RTR 180cc',
     'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
                         'Yamaha FZs 150cc',
            'Honda CB Hornet 160R  ABS DLX',
      'Hero Splendor Plus Self Alloy 100cc',
        'Royal Enfield Thunderbird X 350cc',
 'Royal Enfield Classic Desert Storm 500cc',
 ...
                 'Bajaj Discover150S 150cc',
                       'Hero i Smart 125cc',
               'Hero Splendor Plus  100 cc',
                'Hero Splendor Plus 100 CC',
                      'Hero Karizma 223 cc',
                         'TVS MAX 4R 110cc',
                   'Mahindra Pantero 110cc',
                      'Hero Ambition 135cc',
                'Honda CBR 250R Repsol ABS',
                'Hero Hunk Rear Disc 150cc']
Length: 471, dtype: str

In [31]:
df['bike_name'].nunique()

471

In [32]:
df['bike_name'].value_counts()

bike_name
Royal Enfield Classic 350cc        358
Bajaj Pulsar 150cc                 265
Royal Enfield Thunderbird 350cc    237
Bajaj Avenger 220cc                165
Hero Passion Pro 100cc             160
                                  ...
TVS MAX 4R 110cc                     1
Mahindra Pantero 110cc               1
Hero Ambition 135cc                  1
Honda CBR 250R Repsol ABS            1
Hero Hunk Rear Disc 150cc            1
Name: count, Length: 471, dtype: int64

In [33]:
df["brand"]

0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...
9362               Hero
9369              Bajaj
9370    Harley-Davidson
9371              Bajaj
9372              Bajaj
Name: brand, Length: 7324, dtype: str

In [34]:
df["brand"].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [35]:
df["brand"].nunique()

23

In [36]:
df["brand"].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [39]:
df[df["brand"]=='Bajaj']

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
12,Bajaj Pulsar NS200,78000.0,Bangalore,9900.0,First Owner,4.0,200.0,Bajaj,7.0
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj,11.0
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj,10.0
15,Bajaj Pulsar NS200 ABS,90000.0,Bangalore,11574.0,First Owner,3.0,200.0,Bajaj,6.0
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj,6.0
...,...,...,...,...,...,...,...,...,...
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj,11.0
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj,10.0
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj,12.0
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj,7.0
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj,8.0

In [40]:
Bajaj_df = df[df['brand']=='Bajaj']

In [41]:
Bajaj_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
12,Bajaj Pulsar NS200,78000.0,Bangalore,9900.0,First Owner,4.0,200.0,Bajaj,7.0
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj,11.0
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj,10.0
15,Bajaj Pulsar NS200 ABS,90000.0,Bangalore,11574.0,First Owner,3.0,200.0,Bajaj,6.0
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj,6.0
...,...,...,...,...,...,...,...,...,...
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj,11.0
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj,10.0
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj,12.0
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj,7.0
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj,8.0

In [42]:
kms_df = Bajaj_df[Bajaj_df['kms_driven']<=50000]

In [43]:
kms_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
12,Bajaj Pulsar NS200,78000.0,Bangalore,9900.0,First Owner,4.0,200.0,Bajaj,7.0
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj,11.0
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj,10.0
15,Bajaj Pulsar NS200 ABS,90000.0,Bangalore,11574.0,First Owner,3.0,200.0,Bajaj,6.0
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj,6.0
...,...,...,...,...,...,...,...,...,...
9350,Bajaj Pulsar NS200,46000.0,Bangalore,27687.0,Third Owner,9.0,200.0,Bajaj,12.0
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj,11.0
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj,10.0
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj,7.0
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj,8.0

In [44]:
price_df = kms_df[kms_df['price']<=50000]
price_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj,11.0
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj,10.0
28,Bajaj Pulsar 150cc,50000.0,Bangalore,19000.0,First Owner,8.0,150.0,Bajaj,11.0
32,Bajaj Avenger 220cc,40900.0,Gurgaon,15000.0,First Owner,6.0,220.0,Bajaj,9.0
41,Bajaj Avenger 220cc,45000.0,Hyderabad,36100.0,First Owner,6.0,220.0,Bajaj,9.0
...,...,...,...,...,...,...,...,...,...
9317,Bajaj V15 150cc,50000.0,Bangalore,16674.0,First Owner,4.0,150.0,Bajaj,7.0
9347,Bajaj Discover 125cc,14000.0,Mumbai,39211.0,First Owner,16.0,125.0,Bajaj,19.0
9350,Bajaj Pulsar NS200,46000.0,Bangalore,27687.0,Third Owner,9.0,200.0,Bajaj,12.0
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj,11.0
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj,10.0

In [45]:
owner_df = price_df[price_df['owner']== 'First Owner']
owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj,11.0
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj,10.0
28,Bajaj Pulsar 150cc,50000.0,Bangalore,19000.0,First Owner,8.0,150.0,Bajaj,11.0
32,Bajaj Avenger 220cc,40900.0,Gurgaon,15000.0,First Owner,6.0,220.0,Bajaj,9.0
41,Bajaj Avenger 220cc,45000.0,Hyderabad,36100.0,First Owner,6.0,220.0,Bajaj,9.0
...,...,...,...,...,...,...,...,...,...
9313,Bajaj V15 150cc,42000.0,Mumbai,16539.0,First Owner,5.0,150.0,Bajaj,8.0
9317,Bajaj V15 150cc,50000.0,Bangalore,16674.0,First Owner,4.0,150.0,Bajaj,7.0
9347,Bajaj Discover 125cc,14000.0,Mumbai,39211.0,First Owner,16.0,125.0,Bajaj,19.0
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj,11.0
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj,10.0

In [48]:
Hero_df = df[df['brand']=='Hero']
Hero_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero,6.0
22,Hero Splendor iSmart Plus IBS 110cc,46500.0,Delhi,3500.0,First Owner,2.0,110.0,Hero,5.0
26,Hero Super Splendor 125cc,20000.0,Ahmedabad,29305.0,First Owner,16.0,125.0,Hero,19.0
48,Hero Hunk 150cc,37000.0,Mumbai,10800.0,First Owner,8.0,150.0,Hero,11.0
66,Hero CD Deluxe 100cc,12200.0,Agra,46643.0,First Owner,14.0,100.0,Hero,17.0
...,...,...,...,...,...,...,...,...,...
9316,Hero Glamour Fi 125cc,37000.0,Delhi,28478.0,First Owner,5.0,125.0,Hero,8.0
9339,Hero Splendor Plus 100cc,11400.0,Gurgaon,20000.0,Second Owner,17.0,100.0,Hero,20.0
9341,Hero CD Deluxe 100cc,25000.0,Sidhi,11122.0,First Owner,11.0,100.0,Hero,14.0
9343,Hero Passion Plus 100cc,24000.0,Hyderabad,68000.0,First Owner,14.0,100.0,Hero,17.0
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero,11.0

In [50]:
Price_df = Hero_df[Hero_df['price']<=70000]
Price_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero,6.0
22,Hero Splendor iSmart Plus IBS 110cc,46500.0,Delhi,3500.0,First Owner,2.0,110.0,Hero,5.0
26,Hero Super Splendor 125cc,20000.0,Ahmedabad,29305.0,First Owner,16.0,125.0,Hero,19.0
48,Hero Hunk 150cc,37000.0,Mumbai,10800.0,First Owner,8.0,150.0,Hero,11.0
66,Hero CD Deluxe 100cc,12200.0,Agra,46643.0,First Owner,14.0,100.0,Hero,17.0
...,...,...,...,...,...,...,...,...,...
9316,Hero Glamour Fi 125cc,37000.0,Delhi,28478.0,First Owner,5.0,125.0,Hero,8.0
9339,Hero Splendor Plus 100cc,11400.0,Gurgaon,20000.0,Second Owner,17.0,100.0,Hero,20.0
9341,Hero CD Deluxe 100cc,25000.0,Sidhi,11122.0,First Owner,11.0,100.0,Hero,14.0
9343,Hero Passion Plus 100cc,24000.0,Hyderabad,68000.0,First Owner,14.0,100.0,Hero,17.0
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero,11.0

In [51]:
age_df = Price_df[Price_df['age']<=2]
age_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
22,Hero Splendor iSmart Plus IBS 110cc,46500.0,Delhi,3500.0,First Owner,2.0,110.0,Hero,5.0
121,Hero Splendor iSmart Plus IBS 110cc,48672.0,Ernakulam,608.0,First Owner,2.0,110.0,Hero,5.0
172,Hero Super Splendor 125cc,43778.0,Ernakulam,948.0,First Owner,2.0,125.0,Hero,5.0
176,Hero Splendor Plus Kick Alloy 100cc,48500.0,Delhi,5500.0,First Owner,2.0,100.0,Hero,5.0
197,Hero HF Deluxe i3s iBS 100cc,60000.0,Mumbai,4000.0,First Owner,2.0,100.0,Hero,5.0
328,Hero Passion Xpro 110cc,58000.0,Delhi,7758.0,First Owner,2.0,110.0,Hero,5.0
419,Hero Passion Pro 110cc Drum,56500.0,Delhi,10000.0,First Owner,2.0,110.0,Hero,5.0
492,Hero Splendor Plus IBS i3S 100cc,53300.0,Delhi,10000.0,First Owner,2.0,100.0,Hero,5.0
505,Hero Splendor Plus IBS i3S 100cc,65000.0,Delhi,2600.0,First Owner,2.0,100.0,Hero,5.0
708,Hero Splendor Plus Self Alloy 100cc,51300.0,Palakkad,2800.0,First Owner,2.0,100.0,Hero,5.0
787,Hero Xtreme 200R,66000.0,Faridabad,1112.0,First Owner,2.0,200.0,Hero,5.0
2479,Hero Splendor Plus IBS i3S 100cc,47167.0,Delhi,4664.0,First Owner,2.0,100.0,Hero,5.0
2631,Hero Splendor iSmart Plus IBS 110cc,50000.0,Delhi,11584.0,First Owner,2.0,110.0,Hero,5.0
2654,Hero Passion Pro i3S Alloy 100cc,60000.0,Ghaziabad,1877.0,First Owner,2.0,100.0,Hero,5.0
2952,Hero Passion Pro i3S Alloy 100cc IBS,62000.0,Mumbai,1800.0,First Owner,2.0,100.0,Hero,5.0
3029,Hero HF Deluxe Eco 100cc,55000.0,Gurgaon,2309.0,First Owner,2.0,100.0,Hero,5.0
3298,Hero Splendor Plus IBS i3S 100cc,56000.0,Delhi,1745.0,First Owner,2.0,100.0,Hero,5.0
3882,Hero Splendor Plus Self Alloy 100cc,55000.0,Faridabad,4195.0,First Owner,2.0,100.0,Hero,5.0
4055,Hero Splendor Plus Self Alloy 100cc,55000.0,Gurgaon,5238.0,First Owner,2.0,100.0,Hero,5.0
4512,Hero HF Deluxe Eco 100cc,41000.0,Faridabad,4544.0,First Owner,2.0,100.0,Hero,5.0
5933,Hero Super Splendor 125cc,57000.0,Noida,3200.0,First Owner,2.0,125.0,Hero,5.0
6613,Hero HF Deluxe self Alloy 100cc,39500.0,Faridabad,5448.0,First Owner,2.0,100.0,Hero,5.0
6981,Hero Passion Pro 110cc Drum,56000.0,Delhi,1168.0,First Owner,2.0,110.0,Hero,5.0
7381,Hero HF Deluxe Eco 100cc,46000.0,Faridabad,11309.0,First Owner,2.0,100.0,Hero,5.0

In [53]:
owner_df = age_df[age_df['owner']=='First Owner']
owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
22,Hero Splendor iSmart Plus IBS 110cc,46500.0,Delhi,3500.0,First Owner,2.0,110.0,Hero,5.0
121,Hero Splendor iSmart Plus IBS 110cc,48672.0,Ernakulam,608.0,First Owner,2.0,110.0,Hero,5.0
172,Hero Super Splendor 125cc,43778.0,Ernakulam,948.0,First Owner,2.0,125.0,Hero,5.0
176,Hero Splendor Plus Kick Alloy 100cc,48500.0,Delhi,5500.0,First Owner,2.0,100.0,Hero,5.0
197,Hero HF Deluxe i3s iBS 100cc,60000.0,Mumbai,4000.0,First Owner,2.0,100.0,Hero,5.0
328,Hero Passion Xpro 110cc,58000.0,Delhi,7758.0,First Owner,2.0,110.0,Hero,5.0
419,Hero Passion Pro 110cc Drum,56500.0,Delhi,10000.0,First Owner,2.0,110.0,Hero,5.0
492,Hero Splendor Plus IBS i3S 100cc,53300.0,Delhi,10000.0,First Owner,2.0,100.0,Hero,5.0
505,Hero Splendor Plus IBS i3S 100cc,65000.0,Delhi,2600.0,First Owner,2.0,100.0,Hero,5.0
708,Hero Splendor Plus Self Alloy 100cc,51300.0,Palakkad,2800.0,First Owner,2.0,100.0,Hero,5.0
787,Hero Xtreme 200R,66000.0,Faridabad,1112.0,First Owner,2.0,200.0,Hero,5.0
2479,Hero Splendor Plus IBS i3S 100cc,47167.0,Delhi,4664.0,First Owner,2.0,100.0,Hero,5.0
2631,Hero Splendor iSmart Plus IBS 110cc,50000.0,Delhi,11584.0,First Owner,2.0,110.0,Hero,5.0
2654,Hero Passion Pro i3S Alloy 100cc,60000.0,Ghaziabad,1877.0,First Owner,2.0,100.0,Hero,5.0
2952,Hero Passion Pro i3S Alloy 100cc IBS,62000.0,Mumbai,1800.0,First Owner,2.0,100.0,Hero,5.0
3029,Hero HF Deluxe Eco 100cc,55000.0,Gurgaon,2309.0,First Owner,2.0,100.0,Hero,5.0
3298,Hero Splendor Plus IBS i3S 100cc,56000.0,Delhi,1745.0,First Owner,2.0,100.0,Hero,5.0
3882,Hero Splendor Plus Self Alloy 100cc,55000.0,Faridabad,4195.0,First Owner,2.0,100.0,Hero,5.0
4055,Hero Splendor Plus Self Alloy 100cc,55000.0,Gurgaon,5238.0,First Owner,2.0,100.0,Hero,5.0
4512,Hero HF Deluxe Eco 100cc,41000.0,Faridabad,4544.0,First Owner,2.0,100.0,Hero,5.0
5933,Hero Super Splendor 125cc,57000.0,Noida,3200.0,First Owner,2.0,125.0,Hero,5.0
6613,Hero HF Deluxe self Alloy 100cc,39500.0,Faridabad,5448.0,First Owner,2.0,100.0,Hero,5.0
6981,Hero Passion Pro 110cc Drum,56000.0,Delhi,1168.0,First Owner,2.0,110.0,Hero,5.0
7381,Hero HF Deluxe Eco 100cc,46000.0,Faridabad,11309.0,First Owner,2.0,100.0,Hero,5.0

In [55]:
power_df = owner_df[owner_df['power']>= 150]
power_df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
787,Hero Xtreme 200R,66000.0,Faridabad,1112.0,First Owner,2.0,200.0,Hero,5.0

In [10]:
df.iloc[1]

bike_name     Royal Enfield Classic 350cc
price                            119900.0
city                                Delhi
kms_driven                        11000.0
owner                         First Owner
age                                   4.0
power                               350.0
brand                       Royal Enfield
Name: 1, dtype: object

In [11]:
df[df["age"]>2]

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [12]:
df[df["price"]>90000]

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
11,Yamaha FZ25 250cc,95000.0,Bangalore,9665.0,First Owner,4.0,250.0,Yamaha
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj
...,...,...,...,...,...,...,...,...
32626,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
32627,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [13]:
df["age after 3 years"]=df["age"]+3

In [14]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS,6.0
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield,7.0
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph,11.0
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS,7.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha,6.0
...,...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero,7.0
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS,12.0
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj,9.0
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero,19.0
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj,16.0

In [15]:
df.isnull()

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
32643,False,False,False,False,False,False,False,False,False
32644,False,False,False,False,False,False,False,False,False
32645,False,False,False,False,False,False,False,False,False
32646,False,False,False,False,False,False,False,False,False
32647,False,False,False,False,False,False,False,False,False

In [16]:
df.isnull().sum()

bike_name            0
price                0
city                 0
kms_driven           0
owner                0
age                  0
power                0
brand                0
age after 3 years    0
dtype: int64

In [17]:
df.fillna(1)

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS,6.0
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield,7.0
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph,11.0
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS,7.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha,6.0
...,...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero,7.0
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS,12.0
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj,9.0
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero,19.0
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj,16.0

In [18]:
df.dropna()

,bike_name,price,city,kms_driven,owner,age,power,brand,age after 3 years
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS,6.0
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield,7.0
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph,11.0
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS,7.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha,6.0
...,...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero,7.0
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS,12.0
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj,9.0
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero,19.0
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj,16.0